sudo: false
dist: trusty
language: php

matrix:
  include:
  - php: 7.2

before_script:
- composer install

script:
  - ./vendor/bin/php-cs-fixer fix --dry-run --diff
  - ./vendor/bin/phpstan analyse
  - ./vendor/bin/phpunit
